version: '3'
networks:
  cernunnos-net:
    external: true
    name: cernunnos-net
    driver: bridge

volumes:
  cernunnos-data: {}

services:
  cernunnos:
    container_name: cernunnos
    image: cernunnos:latest
    ports:
      - 8080:8080
    expose: 
      - 8080
    networks:
      - cernunnos-net
    depends_on:
      cernunnos-db:
        condition: service_started

  cernunnos-db:
    container_name: cernunnos-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=cernunnos
      - POSTGRES_PASSWORD=cernunnos
      - POSTGRES_DB=cernunnos
    volumes:
      - cernunnos-data:/var/lib/postgresql/data
      - ./migrations/cernunnos.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - cernunnos-net
    healthcheck:
      test: [ "CMD", "-U", "cernunnos", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s